version: "3.8"
services:

  gateway:
    image: nginx:1.19.8-alpine
    ports:
      - 8080:8080
    networks:
      - backend
    volumes:
      - ./Gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./Gateway/api_gateway.conf:/etc/nginx/api_gateway.conf
      
  admin-request-microservice:
    image: admin-request-microservice:compose_build
    build:
      context: ./admin-request-microservice
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${ADMIN_REQUEST_SERVICE_PORT}
      
  campaign-microservice:
    image: campaign-microservice:compose_build
    build:
      context: ./campaign-microservice
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${CAMPAIGN_SERVICE_PORT}

  message-microservice:
    image: message-microservice:compose_build
    build:
      context: ./message-microservice
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${MESSAGE_SERVICE_PORT}

  post-microservice:
    image: post-microservice:compose_build
    build:
      context: ./post-microservice
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${POST_SERVICE_PORT}

  story-microservice:
    image: story-microservice:compose_build
    build:
      context: ./story-microservice
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${STORY_SERVICE_PORT}

  tag-microservice:
    image: tag-microservice:compose_build
    build:
      context: ./tag-microservice
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${TAG_SERVICE_PORT}

  user-microservice:
    image: user-microservice:compose_build
    build:
      context: ./user-microservice
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${USER_SERVICE_PORT}

  user-request-microservice:
    image: user-request-microservice:compose_build
    build:
      context: ./user-request-microservice
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${USER_REQUEST_SERVICE_PORT}


networks:
  backend:
    name: nistagram
    driver: bridge
