version: "3.8"
services:

  gateway:
    image: nginx:1.19.8-alpine
    ports:
      - 8080:8080
    networks:
      - backend
    volumes:
      - ./Gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./Gateway/api_gateway.conf:/etc/nginx/api_gateway.conf


  user-service:
    image: user-service:compose_build
    build:
      context: ./user-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${USER_SERVICE_PORT}

  user-request-service:
    image: user-request-service:compose_build
    build:
      context: ./user-request-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${USER_REQUEST_SERVICE_PORT}

  tag-service:
    image: tag-service:compose_build
    build:
      context: ./tag-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${TAG_SERVICE_PORT}

  story-service:
    image: story-service:compose_build
    build:
      context: ./story-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${STORY_SERVICE_PORT}

  post-service:
    image: post-service:compose_build
    build:
      context: ./post-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${POST_SERVICE_PORT}

  message-service:
    image: message-service:compose_build
    build:
      context: ./message-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${MESSAGE_SERVICE_PORT}

  campaign-service:
    image: campaign-service:compose_build
    build:
      context: ./campaign-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${CAMPAIGN_SERVICE_PORT}

  admin-request-service:
    image: admin-request-service:compose_build
    build:
      context: ./admin-request-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: ${ADMIN_REQUEST_SERVICE_PORT}
networks:
  backend:
    name: nistagram
    driver: bridge
